language: node_js
node_js:
  - "0.12"
notifications:
  webhooks: https://ohager-nanoflux.getbadges.io/api/app/webhook/1fd7dc46-555b-443a-af2f-a705f8c74935
before_script:
  - npm install -g gulp
script: gulp

